### PR TITLE
Added GoBNB with '5' as identifier

### PR DESCRIPTION
**Pull request by gobnb**
Claiming the identifier '5' for GoBNB app

### CODE REVIEW

**Comment by huangsuyu** [comment]
> Claiming the identifier '5' for GoBNB app

Hello,

It seems 5 is already taken, can you choose another one?

Thanks ^^

**Comment by gobnb** [comment]
Added '7' now.

**Comment by huangsuyu** [comment]
> Added '7' now.

Thanks, LGTM

**Review by jonesk7734 — APPROVED** [review]
😀

**Pull request merged**
