### PR TITLE
BEP8: Mini-BEP2 Tokens

### PR DESCRIPTION
**Pull request by erhenglu**
Similar to SME board in the traditional stock markets, introducing Mini-BEP2 Tokens is to benefit the below scenarios in which the normal BEP2 tokens are expensive and not convenient to issue/list:
- Small enterprise tokens of utility and/or shares
- Point system
- Intellectual Property (IP) tokens

Different from the normal BEP2, using a mini-token system is good at:
- Very cheap (much less than BEP2) to issue tokens, as it takes less network resource
- Easy and very cheap to list tokens, fully self-managed. It does not need to get validators vote to list against BNB and BUSD. 

BEP-8 Proposal describes a common set of rules for Mini-BEP2 token management within the Binance Chain ecosystem. It introduces the following details of Mini-BEP2 token on Binance Chain:
- What information makes a Mini-BEP2 token on Binance Chain
- What actions can be performed on a Mini-BEP2 token on Binance Chain
- How Mini-BEP2 token trading is different from BEP2 token trading

### CODE REVIEW

**Comment by darren-liu** [comment]
This is a good proposal, which potentially brings significant change in Binance Chain token economy. I suggest we reuse some non-used BEP proposal number, such as 8, instead of 69.

**Comment by corollari** [comment]
I propose merging this proposal, given that this has already been made part of the chain (see [this upgrade announcement](https://community.binance.org/topic/2814/binance-chain-testnet-nightingale-upgrade-announcement)). Merging would also fix the currently broken link in the announcement.

**Comment by zaman10d** [comment]
Setup. Quick

**Comment by zaman10d** [comment]
Later comment. Back home

**Review by totongcute — COMMENTED** [review]
.

**Comment by pomnt** [comment]
> Similar to SME board in the traditional stock markets, introducing Mini-BEP2 Tokens is to benefit the below scenarios in which the normal BEP2 tokens are expensive and not convenient to issue/list:
> 
> * Small enterprise tokens of utility and/or shares
> * Point system
> * Intellectual Property (IP) tokens
> 
> Different from the normal BEP2, using a mini-token system is good at:
> 
> * Very cheap (much less than BEP2) to issue tokens, as it takes less network resource
> * Easy and very cheap to list tokens, fully self-managed. It does not need to get validators vote to list against BNB and BUSD.
> 
> BEP-8 Proposal describes a common set of rules for Mini-BEP2 token management within the Binance Chain ecosystem. It introduces the following details of Mini-BEP2 token on Binance Chain:
> 
> * What information makes a Mini-BEP2 token on Binance Chain
> * What actions can be performed on a Mini-BEP2 token on Binance Chain
> * How Mini-BEP2 token trading is different from BEP2 token trading

**Review by DELJUJAZI — COMMENTED** [review]
Tks

**Review by Susypina — APPROVED** [review]

**Comment by blaaauw** [comment]
Hi everyone.

Final stage to transfer assets ,reason I now use the support system of
platforms.


Thanks.

**Comment by Maxim17081983** [comment]
mini_token_bep

**Review by Susypina — APPROVED** [review]

**Comment by kazhall9** [comment]
`i bed for this
`

**Comment by 09168806659** [comment]
mini_token_bep

**Comment by 09168806659** [comment]
mini_token_bep

**Review by japko1980 — APPROVED** [review]

**Comment by atifnimran** [comment]
This is right

**Comment by Cplus360** [comment]
> Similar to SME board in the traditional stock markets, introducing Mini-BEP2 Tokens is to benefit the below scenarios in which the normal BEP2 tokens are expensive and not convenient to issue/list:
> 
> - Small enterprise tokens of utility and/or shares
> 
> - Point system
> 
> - Intellectual Property (IP) tokens
> 
> 
> 
> Different from the normal BEP2, using a mini-token system is good at:
> 
> - Very cheap (much less than BEP2) to issue tokens, as it takes less network resource
> 
> - Easy and very cheap to list tokens, fully self-managed. It does not need to get validators vote to list against BNB and BUSD. 
> 
> 
> 
> BEP-8 Proposal describes a common set of rules for Mini-BEP2 token management within the Binance Chain ecosystem. It introduces the following details of Mini-BEP2 token on Binance Chain:
> 
> - What information makes a Mini-BEP2 token on Binance Chain
> 
> - What actions can be performed on a Mini-BEP2 token on Binance Chain
> 
> - How Mini-BEP2 token trading is different from BEP2 token tr

**Review by alice22foster — COMMENTED** [review]
Ok

**Review by jonesk7734 — APPROVED** [review]
😀

**Review by octavio12345300 — COMMENTED** [review]
list

**Pull request merged**
